* Contacts
  |-----------------+-------+---------------------------+------------|
  | Who             | Where | Email                     | Interests  |
  |-----------------+-------+---------------------------+------------|
  | Fei Chen        | JJIM  | fchen6@its.jnj.com        | Regulatory |
  | Bohdana Ratitch | Bayer | bohdana.ratitch@bayer.com | Outreach   |
  |-----------------+-------+---------------------------+------------|

 - Members
  |----+-----------------------+-------------+----------------------------------+-------------------------------|
  |    | Who                   | Where       | Email                            | Interests                     |
  |----+-----------------------+-------------+----------------------------------+-------------------------------|
  |  1 | Xin Wang              | Abbvie      | xin.wang@abbvie.com              | Site selection                |
  |  2 | Vlad Anisimov         | Amgen       | vanisimo@amgen.com               | Methodology                   |
  |  3 | Christi Kleoudis      | AZ          | christi.kleoudis@astrazeneca.com |                               |
  |  4 | Gabriel Abreu         | AZ          | gabriel.abreu@astrazeneca.com    |                               |
  |  5 | Andrew Chen           | Bayer       | andrew.chen@bayer.com            | Site selection and assessment |
  |  6 | Clara Cali Mella      | Bayer       | clara.calimella@bayer.com        | Recruitment monitoring        |
  |  7 | Tobias Straubinger    | Bayer       | tobias.straubinger@bayer.com     | Forecasting                   |
  |  8 | Kaifeng Lu            | Beonemed    | kaifeng.lu@beonemed.com          | Drug demand forecasting       |
  |  9 | Haoyu Wang            | BMS         | haoyu.wang2@bms.com              |                               |
  | 10 | Inna Perevozskaya     | BMS         | inna.perevozskaya@bms.com        | Methodology                   |
  | 11 | Oleksandr Savenkov    | BMS         | oleksandr.savenkov@bms.com       |                               |
  | 12 | Palanikumar Ravindran | BMS         | palanikumar.ravindran@bms.com    | AI/ML/Viz                     |
  | 13 | Zhuoxin Yu            | BMS         | zhuoxin.yu@bms.com               | AI/ML/Viz                     |
  | 14 | Kyle Wathen           | Cytel       | kyle.wathen@cytel.com            | Software                      |
  | 15 | -Robert Abugov-       | FDA         | robert.abugov@fda.hhs.gov        |                               |
  | 16 | Bhargava Reddy        | JJIM        | breddy1@its.jnj.com              | Operations                    |
  | 17 | Forrest Williamson    | Lilly       | forrest_williamson@lilly.com     | Pediatric                     |
  | 18 | Jun Xing              | Sanofi      | Jun.Xing@sanofi.com              |                               |
  | 19 | Benjamin Hofner       | PEI         | benjamin.hofner@pei.de           | Group Advisor                 |
  | 20 | Cristiana Mayer       | JNJ MedTech | CMayer1@its.jnj.com              |                               |
  | 21 | Bochao Jia            | Lilly       | jia_bochao@lilly.com             | Operational Analytics         |
  |----+-----------------------+-------------+----------------------------------+-------------------------------|
  #+TBLFM: $1=@#-1

* Expertise
  - Volodymyr Anisimov, vanisimov@amgen.com
  - Inna Perevozskaya, inna.perevozskaya@bms.com
  - Kyle Wathen, Kyle.Wathen@cytel.com
  - Clara Cali Mella clara.calimella@bayer.com
    experienced in recruitment monitoring and forecasting, strategic
    data collection and analysis planning and in programming, some experience in site selection and performance assessment
  - Andrew Chen andrew.chen@bayer.com
    experienced in site selection
    and performance assessment, recruitment monitoring and forecasting
    and strategic data collection and analysis planning
  - Tobias Straubinger tobias.straubinger@bayer.com
    experienced in recruitment monitoring and forecasting
  - Wang, Xin xin.wang@abbvie.com
    I’m interested in ‘site selection’, ‘patient population monitoring and forecasting’, ‘RWE and AI/ML tools’. I have done some research in adaptive designs and trial simulations. I also have extensive experience in developing blockbusters such as Humira, Rinvoq and CAR-T cell therapies
  - Palanikumar Ravindran, Palanikumar.Ravindran@bms.com
    Interest in AI, Machine Learning, and Data Visualization: His experience includes using these methodologies to improve clinical trial processes and outcomes. For example, he has used random forests, a machine learning method, to predict key endpoints in virology programs, helping to differentiate between placebo and treatment groups.
    Experience with Bayesian Methodologies: Has led the implementation of Bayesian study designs for phase 2 studies in the CCR8 program. Additionally, he has contributed to several early development research projects, including Bayesian phase 2 designs, optimizing clinical trial strategies.
    Commitment to Improving Efficiency in Clinical Trials: He has passion for improving the efficiency of clinical trial execution. For instance, he led the effort to create templates and provide training for sample size calculations storage and documentation, enhancing operational efficiency in early and late phase oncology studies.
    Experience Across Different Stages of Clinical Trials: His professional experience spans all stages of clinical trials (Phase I to Phase IV). Experienced in designing adaptive trial designs. He has supported both early development and late development for oncology studies. His work at Bristol-Myers Squibb and Hoffmann-La Roche has provided him with a comprehensive understanding of clinical trial execution and operational challenges. Furthermore, it has provided him with proven track record of effectively collaborating with cross-functional teams.
  - Zhuoxin Yu, Zhuoxin.Yu@bms.com
    Interest in AI, Machine Learning, and Data Visualization: She is passionate about learning this area and has experience working with Data visualization and curation through Spotfire or Power BI.
    Commitment to Improving Efficiency in Clinical Trials: She has passion for improving the efficiency of clinical trial execution. In studies she has worked on she has spent extensive time with the team to better understand the data acquisition process. She is known for working closely with the clinical team in ensuring all third-party data (lab/imaging/PK/Biomarker/ IMG) is clean and available at time of DBL. She is also well versed on the EDC system we have. She understands the data process even better than some of the clinical staff.
    Excellent programming skills and understanding of ADaM ana STDM : R, SAS, Python
    Experience Across Different Stages of Clinical Trials: She has extensive experience working on Phase 1 – Phase 3 trials and has experience in submissions. Experienced in designing adaptive trial designs.
  - Kaifeng Lu kaifeng.lu@beonemed.com
   Thank you for sharing the objectives of the working group. I would like to contribute and engage in meaningful discussions.
   With over two decades of experience in the pharmaceutical industry,
   I currently lead statistical modeling and simulations at BeOne
   (formerly BeiGene. I have developed methodologies and created an
   internal R Shiny tool for drug demand forecasting. I am also keen
   to explore statistical innovations in site selection and
   performance assessment. I believe these areas hold significant
   potential for improving trial outcomes, and I would welcome the
   opportunity to learn from and collaborate with others in the group.
  - Skip
    I am part of a working group put together by FDA on aligning Bayesian models with expert opinion, which I believe is a project of the ASA Pediatric Working Group. The main driver is Bob Abugov (Robert.Abugov@fda.hhs.gov). Feel free to reach out. You can copy me and mention my recommendation. Cathy Lee also sent me an FDA announcement for a Bayesian Statistical Analysis (BSA) Demonstration Project (see Bayesian Statistical Analysis (BSA) Demonstration Project | FDA). The operational angle suggests more complex adaptive designs which may be more suited for the CID program. https://www.fda.gov/drugs/development-resources/complex-innovative-trial-design-meeting-program. 
    Reach out to me once you get it started. I am always interested in
   innovative statistical approaches, but whether I can be of help
   remains an open question.      
