* Focus area teams
** Patient recruitment monitoring and forecasting, site selection
|---+-----------------------+-----------|
|   | Name                  | Company   |
|---+-----------------------+-----------|
| 1 | Junxiang Luo/Xin Wang | Abbvie    |
| 2 | Vlad Anisimov         | Amgen     |
| 3 | Clara Cali Mella      | Bayer     |
| 4 | Haoyu Wang            | BMS       |
| 5 | Kyle Wathen           | Cytel     |
| 6 | Bochao Jia            | Lilly     |
| 7 | Guohui Wu             | Regeneron |
|---+-----------------------+-----------|
#+TBLFM: $1=@#-1

** Dynamic trial monitoring/data quality
|---+------------+----------|
|   | Name       | Company  |
|---+------------+----------|
| 1 | Xikun Wu   | Beonemed |
| 2 | Zhuoxin Yu | BMS      |
| 3 | Bochao Jia | Lilly    |
| 4 | Jun Xin    | Sanofi   |
|---+------------+----------|
#+TBLFM: $1=@#-1

** Study design and operations impact
|---+---------------------+---------|
|   | Name                | Company |
|---+---------------------+---------|
| 1 | Vlad Anisimov       | Amgen   |
| 2 | Haoyu Wang          | BMS     |
| 3 | Jessica Cannon-Hill | JNJ     |
|---+---------------------+---------|
#+TBLFM: $1=@#-1

** Clinical supply chain
|---+---------------------+----------|
|   | Name                | Company  |
|---+---------------------+----------|
| 1 | Vlad Anisimov       | Amgen    |
| 2 | Christi Kleoudis    | AZ       |
| 3 | Kaifeng Lu/Xikun Wu | Beonemed |
| 4 | Fei Chen            | JNJ      |
|---+---------------------+----------|
#+TBLFM: $1=@#-1

* Next steps
 General check-in meetings approximately every 4–6 weeks
 separate workstream meetings organized as needed

 


* Focus area teams details
** Patient recruitment monitoring and forecasting, site selection
*** Wang, Xin <xin.wang@abbvie.com>
 1-2 Geographic strategy: country/region/site cap in
  MRCT, retaining representativeness, without any particular
  country/region/site dominating effect
*** Anisimov, Vlad
 1. Time-dependent models, predicting time-dependence at interim time
     Projection at early start when not enough data available, Bayesian techniques
     Site selection with historic data
     Screening/randomization modeling to stop earlier to reduce oversampling.
 2. Sub-group monitoring, to account for time-trends, optimal adjustment of recruitment to be on track, etc.
 3. Optimal cost-time efficient re-projection of recruitment and site selection at interim stage. 
*** Clara Cali Mella <clara.calimella@bayer.com>
 1. Patient recruitment monitoring and forecasting, site selection
	Site Selection: data bases to be used for (i) big trials/conventional indications, (ii) small trials, oncology, rare indications
	Site Selection: quantitative and qualitative analysis for site rankings, criteria to be used
	Site Selection: process definition – how to integrate data and reach out to the sites only when needed? How to lower the site burden?
	Recruitment forecasting: models to be used, different results with different models and parameters
	Recruitment forecasting: how to integrate historical data into the models 
	Recruitment forecasting: how to model for scenarios where sites will recruit 1-3 patients
	Recruitment forecasting: how to model for clusters of countries instead of individual countries
	Recruitment forecasting: how to include diversity targets into the models
	Recruitment forecasting: should we consider recruitment period stages
	Recruitment monitoring: which models to use with actuals
	Recruitment monitoring: is it possible to integrate historical data here
	Recruitment monitoring: when to run the models
	Deliverables and Timeline:
	Best practices for an efficient site selection – guidelines on databases and processes
	Publication on recruitment forecasting – models tested and results
	Publication on recruitment monitoring – models tested and results
*** CG Wang <chenguang.wang@regeneron.com> Guohui Wu <guohui.wu@regeneron.com>
 1. Systematic meta-analysis for evaluating country and site performance for future enrollment planning: 6-9 months for literature review including regulatory documents, running simulation and publish the paper for instruction of appropriate stat analysis of country/site evaluation supporting enrollment strategy.
*** Bochao Jia
*** Wang, Haoyu
** Dynamic trial monitoring/data quality
*** Bochao Jia <jia_bochao@lilly.com>
 2. Dynamic trial monitoring/data quality (first choice)
 1. Patient recruitment monitoring and forecasting, site selection (second choice)
	Early detection of high-risk sites from central monitoring using AI/ML.
	Systematic meta-analysis for evaluating country and site performance for guiding enrollment strategy.
 Early detection of high-risk sites from central monitoring using AI/ML: 1 year with methodology developed and publish paper.
*** Wang, Xin
** Study design and operations impact
*** Cannon-Hill, Jessica [VISUS] <jcannon4@ITS.JNJ.COM>
 3. Study design and operations impact
   How to utilize virtual control arm in complex designs (e.g., adaptive designs, crossovers, platform protocols)
   Deliverables: examples of virtual control arm under various designs. 
*** Wang, Haoyu <Haoyu.Wang2@bms.com>
 1 or 3 (prefer 3 if only one choice)
 1: How best to predict enrollment given too slow/too fast scenarios are not uncommon at all?
 3. How to further facilitate/simplify/remove hurdles when implementing innovative designs (e.g., inferential seamless) given current operational challenges/complexities?
 A white-paper in ~1 year

*** Anisimov, Vlad
** Clinical supply chain
*** Kleoudis, Christi <christi.kleoudis@astrazeneca.com>
 4. Clinical supply chain
 Stakeholder feedback
*** Anisimov, Vlad
*** Chen, Fei
